//! proptest scaffolding for `cli` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: invocations with and without file arguments
// predicate: stdin and file inputs reach the parser with the same bytes
#[test]
fn p1() {
        todo_predicate!("stdin and file inputs reach the parser with the same bytes");
}

// id: p2
// generator: invocations over every output format with and without the flag
// predicate: each requested format renders through its renderer; the default is ascii
#[test]
fn p2() {
        todo_predicate!("each requested format renders through its renderer; the default is ascii");
}

// id: p3
// generator: successful and failing invocations
// predicate: streams and exit codes match the constraint exactly
#[test]
fn p3() {
        todo_predicate!("streams and exit codes match the constraint exactly");
}

// id: p4
// generator: invocations with unknown formats
// predicate: the diagnostic names both the requested and the valid formats and exit code is 2
#[test]
fn p4() {
        todo_predicate!("the diagnostic names both the requested and the valid formats and exit code is 2");
}

// id: p5
// generator: every subcommand and flag combination
// predicate: dispatch, verbosity, and format routing behave per the genesis Guide contract, and init writes the `.genesis/tools.toml` entry
#[test]
fn p5() {
        todo_predicate!("dispatch, verbosity, and format routing behave per the genesis Guide contract, and init writes the `.genesis/tools.toml` entry");
}

// id: p6
// generator: render runs with and without `--json`
// predicate: json mode wraps the result in a genesis Envelope; human mode emits raw bytes identical to non-wrapped output
#[test]
fn p6() {
        todo_predicate!("json mode wraps the result in a genesis Envelope; human mode emits raw bytes identical to non-wrapped output");
}

// id: p7
// generator: misspelled subcommands and flags
// predicate: every misspelling yields a DidYouMean/Fix suggestion naming the closest known name
#[test]
fn p7() {
        todo_predicate!("every misspelling yields a DidYouMean/Fix suggestion naming the closest known name");
}

// id: p8
// generator: environments with and without the oracle toolchain and fresh/stale fixture pins
// predicate: the DoctorReport names each check's status and applies available auto-fixes
#[test]
fn p8() {
        todo_predicate!("the DoctorReport names each check's status and applies available auto-fixes");
}

