//! proptest scaffolding for `ge.ascii_render` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: nodes with every border style
// predicate: each rendered box border matches its declared style
#[test]
fn p1() {
        todo_predicate!("each rendered box border matches its declared style");
}

// id: p2
// generator: graphs with every edge style
// predicate: each edge's glyph run matches the style table byte-for-byte
#[test]
fn p2() {
        todo_predicate!("each edge's glyph run matches the style table byte-for-byte");
}

// id: p3
// generator: one graph rendered via two different construction orders
// predicate: outputs are byte-identical
#[test]
fn p3() {
        todo_predicate!("outputs are byte-identical");
}

// id: p4
// generator: graphs with labelled crossing edges
// predicate: no label cell coincides with a node cell or another label cell
#[test]
fn p4() {
        todo_predicate!("no label cell coincides with a node cell or another label cell");
}

