---- MODULE geasciirender ----
\* Generated by `spk compile` from spec `ge.ascii_render` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"grid_received", "drawing", "ascii_done"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "grid_received"

Next ==
  \* t1: grid_received -> drawing (guard: [[ge.ascii_render.c1]])
  \/ vpc = "grid_received" /\ vpc' = "drawing"
  \* t2: drawing -> ascii_done (guard: [[ge.ascii_render.c2]])
  \/ vpc = "drawing" /\ vpc' = "ascii_done"
  \* t3: ascii_done -> drawing (guard: [[ge.ascii_render.c3]])
  \/ vpc = "ascii_done" /\ vpc' = "drawing"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
