//! proptest scaffolding for `ge.boxart_render` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: nodes with every border style
// predicate: each border style yields its Unicode glyph set, one character per cell
#[test]
fn p1() {
        todo_predicate!("each border style yields its Unicode glyph set, one character per cell");
}

// id: p2
// generator: grids with junctions between borders and edges of mixed styles
// predicate: every junction cell equals the combined glyph for its exact neighbourhood
#[test]
fn p2() {
        todo_predicate!("every junction cell equals the combined glyph for its exact neighbourhood");
}

// id: p3
// generator: graphs with every edge style
// predicate: each edge renders with its documented Unicode line glyphs and arrow heads
#[test]
fn p3() {
        todo_predicate!("each edge renders with its documented Unicode line glyphs and arrow heads");
}

