---- MODULE geboxartrender ----
\* Generated by `spk compile` from spec `ge.boxart_render` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"grid_received", "glyphing", "boxart_done"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "grid_received"

Next ==
  \* t1: grid_received -> glyphing (guard: [[ge.boxart_render.c1]])
  \/ vpc = "grid_received" /\ vpc' = "glyphing"
  \* t2: glyphing -> boxart_done (guard: [[ge.boxart_render.c2]])
  \/ vpc = "glyphing" /\ vpc' = "boxart_done"
  \* t3: boxart_done -> glyphing (guard: [[ge.boxart_render.c3]])
  \/ vpc = "boxart_done" /\ vpc' = "glyphing"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
