//! proptest scaffolding for `ge.cli` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: invocations with and without file arguments
// predicate: stdin and file inputs reach the parser with the same bytes
#[test]
fn p1() {
        todo_predicate!("stdin and file inputs reach the parser with the same bytes");
}

// id: p2
// generator: invocations over every output format with and without the flag
// predicate: each requested format renders through its renderer; the default is ascii
#[test]
fn p2() {
        todo_predicate!("each requested format renders through its renderer; the default is ascii");
}

// id: p3
// generator: successful and failing invocations
// predicate: streams and exit codes match the constraint exactly
#[test]
fn p3() {
        todo_predicate!("streams and exit codes match the constraint exactly");
}

// id: p4
// generator: invocations with unknown formats
// predicate: the diagnostic names both the requested and the valid formats and exit code is 2
#[test]
fn p4() {
        todo_predicate!("the diagnostic names both the requested and the valid formats and exit code is 2");
}

