---- MODULE gecli ----
\* Generated by `spk compile` from spec `ge.cli` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"reading", "rendering", "cli_done", "cli_failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "reading"

Next ==
  \* t1: reading -> rendering (guard: [[ge.cli.c1]])
  \/ vpc = "reading" /\ vpc' = "rendering"
  \* t2: rendering -> cli_done (guard: [[ge.cli.c2]])
  \/ vpc = "rendering" /\ vpc' = "cli_done"
  \* t3: rendering -> cli_failed (guard: [[ge.cli.c2]])
  \/ vpc = "rendering" /\ vpc' = "cli_failed"
  \* t4: cli_failed -> reading (guard: [[ge.cli.c3]])
  \/ vpc = "cli_failed" /\ vpc' = "reading"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
