---- MODULE gecli ----
\* Generated by `spk compile` from spec `ge.cli` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"reading", "rendering", "cli_done", "diagnosing", "cli_failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "reading"

Next ==
  \* t1: reading -> rendering (guard: [[ge.cli.c1]])
  \/ vpc = "reading" /\ vpc' = "rendering"
  \* t2: rendering -> cli_done (guard: [[ge.cli.c2]])
  \/ vpc = "rendering" /\ vpc' = "cli_done"
  \* t3: rendering -> cli_failed (guard: [[ge.cli.c2]])
  \/ vpc = "rendering" /\ vpc' = "cli_failed"
  \* t4: reading -> diagnosing (guard: [[ge.cli.c5]])
  \/ vpc = "reading" /\ vpc' = "diagnosing"
  \* t5: diagnosing -> cli_done (guard: [[ge.cli.c6]])
  \/ vpc = "diagnosing" /\ vpc' = "cli_done"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"cli_failed" :> "An unknown output format produces a diagnostic on stderr naming the requested format and the valid formats, followed by exit code 2."

============================================================================
