//! proptest scaffolding for `ge.dot_parser` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn constructs() -> impl Strategy<Value = String> {
        Just("constructs".into())
    }

}

// id: p1
// generator: DOT headers of both kinds
// predicate: a `graph` header yields a model graph with `type: undirected` set and a `digraph` header yields one with `type` unset
#[test]
fn p1() {
        todo_predicate!("a `graph` header yields a model graph with `type: undirected` set and a `digraph` header yields one with `type` unset");
}

// id: p2
// generator: DOT edge chains under all four header×operator combinations
// predicate: one model edge per arrow, directed exactly when the operator is `->` and undirected when it is `--`, independently of the header
#[test]
fn p2() {
        todo_predicate!("one model edge per arrow, directed exactly when the operator is `->` and undirected when it is `--`, independently of the header");
}

// id: p3
// generator: attribute lists with quoted, escaped, and bare values
// predicate: attribute values land unescaped exactly once on the right object
#[test]
fn p3() {
        todo_predicate!("attribute values land unescaped exactly once on the right object");
}

// id: p4
// generator: named, nested, and bare-scope subgraphs
// predicate: a named subgraph becomes a group with the name verbatim containing only its directly declared nodes (nested nodes belong to the innermost group), and a bare `{ }` scope keeps its nodes ungrouped — though the node preceding the scope is still linked by the scope's inner edge chain, per the oracle's surviving left-edge stack
#[test]
fn p4() {
        todo_predicate!("a named subgraph becomes a group with the name verbatim containing only its directly declared nodes (nested nodes belong to the innermost group), and a bare `{ }` scope keeps its nodes ungrouped — though the node preceding the scope is still linked by the scope's inner edge chain, per the oracle's surviving left-edge stack");
}

proptest! {
    // id: p5
    // generator: record labels with and without ports, HTML-like table labels, and the failing constructs (nameless `subgraph`, malformed HTML-like label, unresolvable port reference)
    // predicate: record and HTML-like table labels split into `name.N` part nodes with port markers stripped and edges reattached to the referenced parts, while the failing constructs each produce the oracle's typed error — tokenizing failures quote the offending input, unresolvable port references name the `base:port` and edge id — and return no partial graph
    #[test]
    fn p5(v0 in spec_gen::constructs()) {
        todo_predicate!("record and HTML-like table labels split into `name.N` part nodes with port markers stripped and edges reattached to the referenced parts, while the failing constructs each produce the oracle's typed error — tokenizing failures quote the offending input, unresolvable port references name the `base:port` and edge id — and return no partial graph");
    }
}

