//! proptest scaffolding for `ge.dot_parser` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

use proptest::prelude::*;

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

/// Generated strategies — one per generator named in the spec rows.
/// Each yields a String (the generator's name; executable
/// fragments bind these directly — Revision 15).
pub mod spec_gen {
    use super::*;

    pub fn constructs() -> impl Strategy<Value = String> {
        Just("constructs".into())
    }

}

// id: p1
// generator: DOT headers of both kinds
// predicate: header kind matches model direction exactly
#[test]
fn p1() {
        todo_predicate!("header kind matches model direction exactly");
}

// id: p2
// generator: DOT edge chains and single edge statements
// predicate: one model edge per arrow with correct endpoints and direction
#[test]
fn p2() {
        todo_predicate!("one model edge per arrow with correct endpoints and direction");
}

// id: p3
// generator: attribute lists with quoted, escaped, and bare values
// predicate: attribute values land unescaped exactly once on the right object
#[test]
fn p3() {
        todo_predicate!("attribute values land unescaped exactly once on the right object");
}

// id: p4
// generator: nested subgraphs with and without cluster names
// predicate: named clusters become groups; anonymous subgraphs keep their nodes ungrouped
#[test]
fn p4() {
        todo_predicate!("named clusters become groups; anonymous subgraphs keep their nodes ungrouped");
}

proptest! {
    // id: p5
    // generator: DOT snippets using out-of-scope constructs (records, HTML labels, ports)
    // predicate: each construct is reported with its name and position, and no partial graph is returned
    #[test]
    fn p5(v0 in spec_gen::constructs()) {
        todo_predicate!("each construct is reported with its name and position, and no partial graph is returned");
    }
}

