---- MODULE gedotparser ----
\* Generated by `spk compile` from spec `ge.dot_parser` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"reading", "accepted", "dot_rejected"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "reading"

Next ==
  \* t1: reading -> accepted (guard: [[ge.dot_parser.c1]])
  \/ vpc = "reading" /\ vpc' = "accepted"
  \* t2: reading -> dot_rejected (guard: [[ge.dot_parser.c1]])
  \/ vpc = "reading" /\ vpc' = "dot_rejected"
  \* t3: accepted -> reading (guard: [[ge.dot_parser.c3]])
  \/ vpc = "accepted" /\ vpc' = "reading"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"dot_rejected" :> "A record label — a `shape=record` node whose label contains a vertical bar — or an HTML-like table label parses into numbered part nodes named `name.N`, with port markers stripped and edges reattached to the referenced part; a construct the parser cannot tokenize — such as the `subgraph` keyword without a name or a malformed HTML-like label — and a port reference with no matching part fail with a typed error, and no partial graph is returned."

============================================================================
