//! proptest scaffolding for `ge.graphviz_render` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: arbitrary graphs with quoted, spaced, and unicode node names
// predicate: each node appears exactly once with its quoted name and mapped attributes
#[test]
fn p1() {
        todo_predicate!("each node appears exactly once with its quoted name and mapped attributes");
}

// id: p2
// generator: graphs with directed, undirected, and styled edges
// predicate: arrow type and attribute mapping match the model exactly
#[test]
fn p2() {
        todo_predicate!("arrow type and attribute mapping match the model exactly");
}

// id: p3
// generator: graphs with named and anonymous groups
// predicate: cluster membership equals group membership and anonymous clusters get `cluster<N>` names in internal-id order
#[test]
fn p3() {
        todo_predicate!("cluster membership equals group membership and anonymous clusters get `cluster<N>` names in internal-id order");
}

// id: p4
// generator: arbitrary graphs rendered to DOT and re-parsed
// predicate: the re-parsed model is isomorphic to the source model
#[test]
fn p4() {
        todo_predicate!("the re-parsed model is isomorphic to the source model");
}

