---- MODULE gegraphmodel ----
\* Generated by `spk compile` from spec `ge.graph_model` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"initial", "populated", "mutating", "ready"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "initial"

Next ==
  \* t1: initial -> populated (guard: [[ge.graph_model.c1]])
  \/ vpc = "initial" /\ vpc' = "populated"
  \* t2: populated -> mutating (guard: [[ge.graph_model.c3]])
  \/ vpc = "populated" /\ vpc' = "mutating"
  \* t3: mutating -> populated (guard: [[ge.graph_model.c2]])
  \/ vpc = "mutating" /\ vpc' = "populated"
  \* t4: mutating -> ready (guard: [[ge.graph_model.c4]])
  \/ vpc = "mutating" /\ vpc' = "ready"
  \* t5: ready -> mutating (guard: [[ge.graph_model.c4]])
  \/ vpc = "ready" /\ vpc' = "mutating"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
