---- MODULE gegraphvizrender ----
\* Generated by `spk compile` from spec `ge.graphviz_render` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"model_received", "emitting", "dot_done"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "model_received"

Next ==
  \* t1: model_received -> emitting (guard: [[ge.graphviz_render.c1]])
  \/ vpc = "model_received" /\ vpc' = "emitting"
  \* t2: emitting -> dot_done (guard: [[ge.graphviz_render.c2]])
  \/ vpc = "emitting" /\ vpc' = "dot_done"
  \* t3: dot_done -> emitting (guard: [[ge.graphviz_render.c3]])
  \/ vpc = "dot_done" /\ vpc' = "emitting"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
