//! proptest scaffolding for `ge.html_render` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: arbitrary laid-out graphs
// predicate: td count equals grid size (the documented one-td-per-cell simplification, not the oracle's colspan=4 rowspan=4 span) and each td carries the right content class
#[test]
fn p1() {
        todo_predicate!("td count equals grid size (the documented one-td-per-cell simplification, not the oracle's colspan=4 rowspan=4 span) and each td carries the right content class");
}

// id: p2
// generator: nodes with plain labels, link attributes, and labels containing `&`, `<`, `>`, quotes
// predicate: labels render HTML-escaped and links follow the observed escaping rule (space→+, '→%27, raw `&`)
#[test]
fn p2() {
        todo_predicate!("labels render HTML-escaped and links follow the observed escaping rule (space→+, '→%27, raw `&`)");
}

// id: p3
// generator: graphs with every edge style
// predicate: edge cells carry the documented CSS classes
#[test]
fn p3() {
        todo_predicate!("edge cells carry the documented CSS classes");
}

// id: p4
// generator: rendered tables and documents of arbitrary graphs
// predicate: the table renders bare (no CSS, as upstream `as_html`) and every class referenced in the table has a matching CSS rule in the document's `<style>` block
#[test]
fn p4() {
        todo_predicate!("the table renders bare (no CSS, as upstream `as_html`) and every class referenced in the table has a matching CSS rule in the document's `<style>` block");
}

// id: p5
// generator: nodes and edges with named, rgb, and hex colors plus every shape
// predicate: colors appear as the upstream CSS declarations and shapes carry their documented classes
#[test]
fn p5() {
        todo_predicate!("colors appear as the upstream CSS declarations and shapes carry their documented classes");
}

