---- MODULE gelayout ----
\* Generated by `spk compile` from spec `ge.layout` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"initial", "ranked", "ordered", "positioned", "routed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "initial"

Next ==
  \* t1: initial -> ranked (guard: [[ge.layout.c1]])
  \/ vpc = "initial" /\ vpc' = "ranked"
  \* t2: ranked -> ordered (guard: [[ge.layout.c3]])
  \/ vpc = "ranked" /\ vpc' = "ordered"
  \* t3: ordered -> positioned (guard: [[ge.layout.c2]])
  \/ vpc = "ordered" /\ vpc' = "positioned"
  \* t4: positioned -> routed (guard: [[ge.layout.c4]])
  \/ vpc = "positioned" /\ vpc' = "routed"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
