//! proptest scaffolding for `ge.layout` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: arbitrary graphs laid out twice under identical options
// predicate: both runs produce byte-identical grid outputs
#[test]
fn p1() {
        todo_predicate!("both runs produce byte-identical grid outputs");
}

// id: p2
// generator: arbitrary graphs including dense and wide ones
// predicate: the produced grid contains no node cell overlap
#[test]
fn p2() {
        todo_predicate!("the produced grid contains no node cell overlap");
}

// id: p3
// generator: graphs with all four flow directions
// predicate: every edge's source precedes its target along the flow axis
#[test]
fn p3() {
        todo_predicate!("every edge's source precedes its target along the flow axis");
}

// id: p4
// generator: graphs with labelled, self-loop, and multi edges
// predicate: each edge's routed path is orthogonal, connected, and passes through its label
#[test]
fn p4() {
        todo_predicate!("each edge's routed path is orthogonal, connected, and passes through its label");
}

// id: p5
// generator: renderer-style consumers reading the grid output contract
// predicate: every consumer read matches the layout's own inspection of grid, extents, and paths
#[test]
fn p5() {
        todo_predicate!("every consumer read matches the layout's own inspection of grid, extents, and paths");
}

// id: p6
// generator: large arbitrary graphs with dense crossing regions
// predicate: each stage's running time stays within its polynomial bound
#[test]
fn p6() {
        todo_predicate!("each stage's running time stays within its polynomial bound");
}

