---- MODULE georacle ----
\* Generated by `spk compile` from spec `ge.oracle` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"clean", "verified", "stale", "oracle_missing"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "clean"

Next ==
  \* t1: clean -> verified (guard: [[ge.oracle.c1]])
  \/ vpc = "clean" /\ vpc' = "verified"
  \* t2: clean -> oracle_missing (guard: [[ge.oracle.c1]])
  \/ vpc = "clean" /\ vpc' = "oracle_missing"
  \* t3: verified -> stale (guard: [[ge.oracle.c2]])
  \/ vpc = "verified" /\ vpc' = "stale"
  \* t4: stale -> clean (guard: [[ge.oracle.c3]])
  \/ vpc = "stale" /\ vpc' = "clean"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
