//! proptest scaffolding for `ge.oracle` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: fixture headers recorded by the oracle runner
// predicate: every header names the pinned version and commit; none carries a foreign pin
#[test]
fn p1() {
        todo_predicate!("every header names the pinned version and commit; none carries a foreign pin");
}

// id: p2
// generator: arbitrary fixture inputs across all supported formats
// predicate: every input/format pair has exactly one recorded expected output and no orphans
#[test]
fn p2() {
        todo_predicate!("every input/format pair has exactly one recorded expected output and no orphans");
}

// id: p3
// generator: fixture corpus verified against recorded outputs
// predicate: identical outputs pass; a single byte difference fails with input, format, and first differing line
#[test]
fn p3() {
        todo_predicate!("identical outputs pass; a single byte difference fails with input, format, and first differing line");
}

// id: p4
// generator: environments missing perl, with a drifted Graph::Easy, and with stale pins
// predicate: each case yields a typed error naming the missing piece and the remediation
#[test]
fn p4() {
        todo_predicate!("each case yields a typed error naming the missing piece and the remediation");
}

// id: p5
// generator: record runs with matching and mismatching pins
// predicate: new inputs are recorded and headers updated atomically; pin-less re-recording is rejected
#[test]
fn p5() {
        todo_predicate!("new inputs are recorded and headers updated atomically; pin-less re-recording is rejected");
}

// id: p6
// generator: the recorded corpus coverage matrix
// predicate: every style, shape, group, direction, and label class appears in at least one fixture
#[test]
fn p6() {
        todo_predicate!("every style, shape, group, direction, and label class appears in at least one fixture");
}

// id: p7
// generator: the corpus stability and envelope probes over every fixture input
// predicate: each fixture is classified hash-stable or hash-dependent and inside or outside the envelope; every byte-compat claim references only the stable, in-scope class, and the classification is machine-checkable by the repro-probe harness
#[test]
fn p7() {
        todo_predicate!("each fixture is classified hash-stable or hash-dependent and inside or outside the envelope; every byte-compat claim references only the stable, in-scope class, and the classification is machine-checkable by the repro-probe harness");
}

