---- MODULE geperf ----
\* Generated by `spk compile` from spec `ge.perf` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"idle", "measured", "budget_exceeded"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "idle"

Next ==
  \* t1: idle -> measured (guard: [[ge.perf.c1]])
  \/ vpc = "idle" /\ vpc' = "measured"
  \* t2: idle -> budget_exceeded (guard: [[ge.perf.c1]])
  \/ vpc = "idle" /\ vpc' = "budget_exceeded"
  \* t3: measured -> idle (guard: [[ge.perf.c3]])
  \/ vpc = "measured" /\ vpc' = "idle"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
