//! proptest scaffolding for `ge.perf` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: repeated cold-start runs over budget-class inputs
// predicate: median wall time stays under 50 ms with no run above 3x the median budget
#[test]
fn p1() {
        todo_predicate!("median wall time stays under 50 ms with no run above 3x the median budget");
}

// id: p2
// generator: large graphs around the 1,000-node/2,000-edge class
// predicate: every supported format renders within the wall-time and RSS budgets
#[test]
fn p2() {
        todo_predicate!("every supported format renders within the wall-time and RSS budgets");
}

// id: p3
// generator: stage-by-stage memory profiling over growing inputs
// predicate: peak allocation matches the O(nodes + edges + cells) profile; no cross-stage cache growth
#[test]
fn p3() {
        todo_predicate!("peak allocation matches the O(nodes + edges + cells) profile; no cross-stage cache growth");
}

// id: p4
// generator: deliberately throttled stages exceeding each budget
// predicate: the diagnostic names stage, budget, and measured value, and the exit code is non-zero
#[test]
fn p4() {
        todo_predicate!("the diagnostic names stage, budget, and measured value, and the exit code is non-zero");
}

// id: p5
// generator: input sizes sweeping two orders of magnitude beyond the budget classes
// predicate: measured scaling stays near-linear; deviations beyond the bound are reported
#[test]
fn p5() {
        todo_predicate!("measured scaling stays near-linear; deviations beyond the bound are reported");
}

