//! proptest scaffolding for `ge.txt_render` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: graphs with class attributes on every class
// predicate: class sections appear first, sorted, with sorted attributes
#[test]
fn p1() {
        todo_predicate!("class sections appear first, sorted, with sorted attributes");
}

// id: p2
// generator: arbitrary graphs of nodes, edges, and styles
// predicate: every object appears exactly once with a correct operator form
#[test]
fn p2() {
        todo_predicate!("every object appears exactly once with a correct operator form");
}

// id: p3
// generator: arbitrary graphs serialized then re-parsed
// predicate: the re-parsed model is equal to the source model under the model-equality predicate for the parser-supported subset — group membership excepted (emitted group sections are empty, so members do not round-trip)
#[test]
fn p3() {
        todo_predicate!("the re-parsed model is equal to the source model under the model-equality predicate for the parser-supported subset — group membership excepted (emitted group sections are empty, so members do not round-trip)");
}

// id: p4
// generator: the recorded upstream fixture corpus
// predicate: every fixture's expected canonical text matches gently's output byte-for-byte
#[test]
fn p4() {
        todo_predicate!("every fixture's expected canonical text matches gently's output byte-for-byte");
}

