---- MODULE getextparser ----
\* Generated by `spk compile` from spec `ge.text_parser` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"clean", "accepted", "parse_failed"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "clean"

Next ==
  \* t1: clean -> accepted (guard: [[ge.text_parser.c1]])
  \/ vpc = "clean" /\ vpc' = "accepted"
  \* t2: clean -> parse_failed (guard: [[ge.text_parser.c1]])
  \/ vpc = "clean" /\ vpc' = "parse_failed"
  \* t3: accepted -> clean (guard: [[ge.text_parser.c3]])
  \/ vpc = "accepted" /\ vpc' = "clean"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* One entry per state with an `emits` field — domain is exactly
\* the emitting states; each value is the effect-Constraint's expr.
Output ==
"parse_failed" :> "A malformed input line produces a typed parse error naming the source line number and the reason."

============================================================================
