//! proptest scaffolding for `ge.text_parser` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: arbitrary node tokens, named and anonymous
// predicate: every named bracket token yields a model node with that name, reused by later references; every bare `[ ]` yields an anonymous node named `#N` (odd counter) that `node('#N')` finds and that a later escaped `[ \#N ]` reference reuses as the same node
#[test]
fn p1() {
        todo_predicate!("every named bracket token yields a model node with that name, reused by later references; every bare `[ ]` yields an anonymous node named `#N` (odd counter) that `node('#N')` finds and that a later escaped `[ \\#N ]` reference reuses as the same node");
}

// id: p2
// generator: arbitrary operator patterns from the style grammar, directed and bidirectional, with and without both endpoint nodes
// predicate: each valid operator maps to the documented style; `<`-prefixed operators map to the same style with the edge marked bidirectional; a `<` without a closing `>` and an operator with a missing endpoint node are rejected; style-only styles are accepted via the attribute and rejected as operators
#[test]
fn p2() {
        todo_predicate!("each valid operator maps to the documented style; `<`-prefixed operators map to the same style with the edge marked bidirectional; a `<` without a closing `>` and an operator with a missing endpoint node are rejected; style-only styles are accepted via the attribute and rejected as operators");
}

// id: p9
// generator: directed and arrow-less unit-token patterns, single and repeated
// predicate: the style follows the last unit token; single-unit arrow-less `.-`/`..-` are accepted; plain units are rejected below two repetitions
#[test]
fn p9() {
        todo_predicate!("the style follows the last unit token; single-unit arrow-less `.-`/`..-` are accepted; plain units are rejected below two repetitions");
}

// id: p3
// generator: arbitrary node chains of length 1 to N
// predicate: the parsed model has exactly one edge per adjacent pair and shared endpoints for repeated names
#[test]
fn p3() {
        todo_predicate!("the parsed model has exactly one edge per adjacent pair and shared endpoints for repeated names");
}

// id: p4
// generator: labelled edges with matching, mismatching, and arrow-less flanking patterns
// predicate: valid labelled arrows set the edge label; mismatched flanks and arrow-less inline labels are rejected
#[test]
fn p4() {
        todo_predicate!("valid labelled arrows set the edge label; mismatched flanks and arrow-less inline labels are rejected");
}

// id: p5
// generator: attribute blocks and class sections over all class scopes
// predicate: each attribute lands on exactly the nearest preceding object or the declared class
#[test]
fn p5() {
        todo_predicate!("each attribute lands on exactly the nearest preceding object or the declared class");
}

// id: p6
// generator: group blocks, nested groups, anonymous groups, and multi-group references
// predicate: the group name includes the colon; a node's membership equals the directly declared group it was last declared in; nested inner nodes belong only to the inner group; anonymous groups are named `Group #N`
#[test]
fn p6() {
        todo_predicate!("the group name includes the colon; a node's membership equals the directly declared group it was last declared in; nested inner nodes belong only to the inner group; anonymous groups are named `Group #N`");
}

// id: p7
// generator: inputs with interleaved comments, quoted strings containing `#`, and hex colour values
// predicate: an unescaped `#` truncates the line to a parse error even inside quotes; `\#` survives into attribute values; a hex colour token after an attribute separator is accepted
#[test]
fn p7() {
        todo_predicate!("an unescaped `#` truncates the line to a parse error even inside quotes; `\\#` survives into attribute values; a hex colour token after an attribute separator is accepted");
}

// id: p8
// generator: malformed inputs: bad operators, dangling brackets, unknown classes
// predicate: each error names a line number and a reason and aborts without producing a graph
#[test]
fn p8() {
        todo_predicate!("each error names a line number and a reason and aborts without producing a graph");
}

// id: p10
// generator: attribute values in double-, single-, mixed-, and unterminated-quoted form, with mid-value quotes and escaped `\"`, `\'`, `\;`, `\\` sequences
// predicate: single-quoted and mixed-end values lose their outer quotes; an unterminated quoted value keeps its quotes and ends at the first unescaped `;`; `\"`, `\'`, `\;`, and `\\` become their bare characters; mid-value quotes and `;` inside properly closed quotes survive
#[test]
fn p10() {
        todo_predicate!("single-quoted and mixed-end values lose their outer quotes; an unterminated quoted value keeps its quotes and ends at the first unescaped `;`; `\\\"`, `\\'`, `\\;`, and `\\\\` become their bare characters; mid-value quotes and `;` inside properly closed quotes survive");
}

