---- MODULE getxtrender ----
\* Generated by `spk compile` from spec `ge.txt_render` — source of truth is the
\* spec file; edit there, not here. Extends nothing: the module is
\* self-contained so any engine can open it.

\* No executable invariant fragments (Revision 15).

\* Each State becomes a value in the state variable's range.
StateValues == {"model_received", "serializing", "txt_done"}

VARIABLES vpc   \* the state variable (program counter)

vars == <<vpc>>

TypeOK == vpc \in StateValues

\* Initial state: first listed in the spec (the format has no explicit initial marker).
Init == vpc = "model_received"

Next ==
  \* t1: model_received -> serializing (guard: [[ge.txt_render.c1]])
  \/ vpc = "model_received" /\ vpc' = "serializing"
  \* t2: serializing -> txt_done (guard: [[ge.txt_render.c2]])
  \/ vpc = "serializing" /\ vpc' = "txt_done"
  \* t3: txt_done -> serializing (guard: [[ge.txt_render.c3]])
  \/ vpc = "txt_done" /\ vpc' = "serializing"
  \* stuttering: guards are prose (uninterpreted) — a terminal
  \* state must not read as an engine-side deadlock
  \/ UNCHANGED vpc

\* No state carries an `emits` field — Output is simply empty.
Output == << >>

============================================================================
