//! proptest scaffolding for `ge.text_parser` — generated by `spk compile`.
//! Source of truth: the spec file itself — edit there, not here.
//! Each block quotes its row's generator and predicate verbatim;
//! a predicate opting in with the **rust:** marker (executable
//! fragment, specodelic.md Revision 15) is emitted verbatim as the
//! block's assertion body; predicates not yet translated fail in
//! `verify` via `todo_predicate!`, never at artifact emission.

/// Marker for predicates not yet translated to Rust: compiles here,
/// panics when executed — execution is `verify`'s job. A predicate
/// opting in with **rust:** compiles as a real assertion instead
/// (executable predicate fragment, specodelic.md Revision 15).
macro_rules! todo_predicate {
    ($reason:expr) => { todo!("{}", $reason) };
}

// id: p1
// generator: arbitrary node tokens, named and anonymous
// predicate: every named bracket token yields a model node with that name; every bare `[ ]` yields a node that is never reused by a later reference
#[test]
fn p1() {
        todo_predicate!("every named bracket token yields a model node with that name; every bare `[ ]` yields a node that is never reused by a later reference");
}

// id: p2
// generator: arbitrary operator patterns from the style grammar
// predicate: each valid operator maps to the documented style; style-only styles are accepted via the attribute and rejected as operators
#[test]
fn p2() {
        todo_predicate!("each valid operator maps to the documented style; style-only styles are accepted via the attribute and rejected as operators");
}

// id: p9
// generator: repeated and arrow-less operator patterns, valid and invalid
// predicate: each invalid repetition is rejected and each valid repetition parses to the right style
#[test]
fn p9() {
        todo_predicate!("each invalid repetition is rejected and each valid repetition parses to the right style");
}

// id: p3
// generator: arbitrary node chains of length 1 to N
// predicate: the parsed model has exactly one edge per adjacent pair and shared endpoints for repeated names
#[test]
fn p3() {
        todo_predicate!("the parsed model has exactly one edge per adjacent pair and shared endpoints for repeated names");
}

// id: p4
// generator: labelled edges with matching, mismatching, and arrow-less flanking patterns
// predicate: valid labelled arrows set the edge label; mismatched flanks and arrow-less inline labels are rejected
#[test]
fn p4() {
        todo_predicate!("valid labelled arrows set the edge label; mismatched flanks and arrow-less inline labels are rejected");
}

// id: p5
// generator: attribute blocks and class sections over all class scopes
// predicate: each attribute lands on exactly the nearest preceding object or the declared class
#[test]
fn p5() {
        todo_predicate!("each attribute lands on exactly the nearest preceding object or the declared class");
}

// id: p6
// generator: group blocks, nested groups, and anonymous groups
// predicate: group membership in the model equals the nodes declared inside the block
#[test]
fn p6() {
        todo_predicate!("group membership in the model equals the nodes declared inside the block");
}

// id: p7
// generator: inputs with interleaved comments and quoted strings containing `#`
// predicate: comments are dropped and in-string `#` characters survive into attribute values
#[test]
fn p7() {
        todo_predicate!("comments are dropped and in-string `#` characters survive into attribute values");
}

// id: p8
// generator: malformed inputs: bad operators, dangling brackets, unknown classes
// predicate: each error names a line number and a reason and aborts without producing a graph
#[test]
fn p8() {
        todo_predicate!("each error names a line number and a reason and aborts without producing a graph");
}

